### ISSUE TITLE
GuestOperationsUnavailable

### ISSUE THREAD

**Issue by KevinCooper** [rocky1109/pyVirtualize#8]
When using pyVirtualize, the library does not believe that guest operations are available when attempting to utilize **download** or **upload** in the **yVirtualize.pyvSphere.vm.operation.file.FileOperations** class.  This occurs after reseting the VMs with the following two commands.   All the machines are running and waiting at the login screen.
```python
vm.operations.snapshot.revert_to_current()
vm.operations.power.power_on(wait_for_guest_ready=False)
```

If the `wait_for_guest_ready=False` is set to `True`, then the code never finished the `power_on` sequence.

```python
Traceback (most recent call last):
  File "program.py", line 157, in <module>
    executePlugin(f, vsphere, vmList)
  File "program.py", line 92, in executePlugin
    uploadFile(user, password, src_file, dest_path, vm, vsphere)
  File "program.py", line 58, in uploadFile
    vm.operations.file.download(src_file, dest_path)
  File "C:\path\python3-7\lib\site-packages\pyVirtualize\pyvSphere\vm\operation\file.py", line 186, in download
    if not self.remote_path_exists(src, credentials=credentials):
  File "C:\path\python3-7\lib\site-packages\pyVirtualize\pyvSphere\vm\operation\file.py", line 275, in remote_path_exists
    fi, di = self.get_remote_dir_desc(os.path.dirname(path), credentials)
  File "C:\path\python3-7\lib\site-packages\pyVirtualize\pyvSphere\vm\operation\file.py", line 223, in get_remote_dir_desc
    file_list = self.list_dir_in_vm(path, credentials)
  File "C:\path\python3-7\lib\site-packages\pyVirtualize\pyvSphere\vm\operation\file.py", line 218, in list_dir_in_vm
    filePath=path
  File "C:\path\python3-7\lib\site-packages\pyVmomi\VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "C:\path\python3-7\lib\site-packages\pyVmomi\VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "C:\path\python3-7\lib\site-packages\pyVmomi\SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.GuestOperationsUnavailable: (vim.fault.GuestOperationsUnavailable) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'The guest operations agent could not be contacted.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}
```

**Comment by KevinCooper** [comment]
This also occurs if `vm.operations.power.power_on(wait_for_guest_ready=True)` is the revert command.
